//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Details
    {
        public int TempID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public string Category_Name { get; set; }
    }
}
